//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        public string nid { get; set; }
        public string fname { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public double lat { get; set; }
        public double lang { get; set; }
        public string professin { get; set; }
        public string email { get; set; }
        public string affiliation { get; set; }
        public string password { get; set; }
        public string healthStatus { get; set; }
    }
}
